name: github-action-tutorial-2024

on:
  push:
    branches:
      - main

jobs:
  setup: #job의 이름
    runs-on: ubuntu-latest #가상환경의 OS
    steps:
      - uses: actions/checkout@v4 #git repo 가져오기

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2 #bun에서 가져오기
        with:
          bun-version: '1.1.26' #버전 작성

      - run: bun install

  test:
    runs-on: ubuntu-latest
    needs: setup #셋업에 의존한다
    steps:
      - uses: actions/checkout@v4

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Bun 환경검증
        run: bun --version

      - name: 테스트 수행
        run: bun test
