name: github-action-tutorial-2024

on:
  push:
    branches:
      - main

jobs:
  setup: #job의 이름
    runs-on: ubuntu-latest #가상환경의 OS
    steps:
      - uses: actions/checkout@v4 #git repo 가져오기

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2 #bun에서 가져오기
        with:
          bun-version: '1.1.26' #버전 작성

      - run: bun install

  test:
    runs-on: ubuntu-latest
    needs: setup #셋업에 의존한다
    steps:
      - uses: actions/checkout@v4

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.26'

      - name: Bun 환경검증
        run: bun --version

      - name: 테스트 수행
        run: bun test

  deploy:
    runs-on: ubuntu-latest
    needs: [ setup, test ]
    steps:
      - uses: actions/checkout@v4

      - name: Bun 셋업
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.26'

      - name: Node.js 셋업
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Bun 환경검증
        run: bun --version

      - name: SSH 셋업
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH 파일 저장
        run: |
          echo "${{ secreats.SSH_PRIVATE_KEY }}" > /tmp/new_id
          chmod 600 /tmp/new_id

      - name: Bastion 연결 테스트
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/new_id \
            ${{ secrets.SSH_BASTION_USER }}@${{ secrets.SSH_BASTION_HOST }} -p 10020 "echo Bastion에 연결 성공"
